#!/usr/bin/env bash
set -euo pipefail

# BONNIE Install Script — generated by the FLAG control plane (flag-commons)
# Downloads the latest BONNIE binary and registers with the control plane.

REPO={{.BinaryRepo}}
SERVER_URL={{.ServerURL}}
REGISTRATION_TOKEN={{.RegistrationToken}}
PORT={{.Port}}

INSTALL_DIR="/usr/local/bin"
SERVICE_USER="bonnie"
CONFIG_DIR="/etc/bonnie"

# Files created below (config, downloads) must never be readable by other users.
umask 077

# --- Prerequisites -----------------------------------------------------------

if [ "$(id -u)" -ne 0 ]; then
    echo "Error: This script must be run as root (use sudo)."
    exit 1
fi

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
if [ "$OS" != "linux" ]; then
    echo "Error: This install script is for Linux only."
    exit 1
fi

if ! command -v curl &>/dev/null; then
    echo "Error: curl is required but not installed."
    exit 1
fi

if ! command -v docker &>/dev/null; then
    echo "Error: Docker is required but not installed."
    exit 1
fi

if ! command -v openssl &>/dev/null; then
    echo "Error: openssl is required but not installed."
    exit 1
fi

# --- Parse arguments ----------------------------------------------------------

ADDRESS=""
while [ $# -gt 0 ]; do
    case "$1" in
        --address)
            ADDRESS="$2"
            shift 2
            ;;
        --address=*)
            ADDRESS="${1#*=}"
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# --- Architecture detection ---------------------------------------------------

ARCH=$(uname -m)
case "$ARCH" in
    x86_64)  ARCH="amd64" ;;
    aarch64) ARCH="arm64" ;;
    *)
        echo "Unsupported architecture: $ARCH"
        exit 1
        ;;
esac

echo "Installing BONNIE for ${OS}/${ARCH}..."

# --- Download binary ----------------------------------------------------------

LATEST=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" | grep -m1 '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
if [ -z "$LATEST" ]; then
    echo "Failed to determine latest release."
    exit 1
fi
case "$LATEST" in
    *[!A-Za-z0-9._-]*|.*)
        echo "Refusing unexpected release tag: ${LATEST}"
        exit 1
        ;;
esac
echo "Latest release: ${LATEST}"

# Download into a private temp dir (never a predictable path under /tmp),
# then install root-owned and executable in one step.
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT
BINARY_URL="https://github.com/${REPO}/releases/download/${LATEST}/bonnie-${OS}-${ARCH}"
echo "Downloading ${BINARY_URL}..."
curl -fsSL -o "${TMP_DIR}/bonnie" "$BINARY_URL"
install -o root -g root -m 0755 "${TMP_DIR}/bonnie" "${INSTALL_DIR}/bonnie"
echo "Installed bonnie to ${INSTALL_DIR}/bonnie"

# --- Service user -------------------------------------------------------------

if ! id -u "$SERVICE_USER" &>/dev/null; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
    echo "Created service user: ${SERVICE_USER}"
fi
# Docker socket access is root-equivalent; the systemd hardening below limits
# the filesystem, not what the agent can do through Docker.
usermod -aG docker "$SERVICE_USER"

# --- Generate auth token ------------------------------------------------------

AUTH_TOKEN=$(openssl rand -hex 32)

# --- Configuration ------------------------------------------------------------

mkdir -p -m 700 "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
cat > "${CONFIG_DIR}/bonnie.env" <<ENVEOF
# BONNIE Configuration — managed by install script
BONNIE_AUTH_TOKEN=${AUTH_TOKEN}
BONNIE_LISTEN_ADDR=:${PORT}
BONNIE_POLL_INTERVAL=10
LOG_LEVEL=info
LOG_FORMAT=json
ENVEOF
# Readable by the service, writable only by root.
chown root:"$SERVICE_USER" "${CONFIG_DIR}/bonnie.env"
chmod 640 "${CONFIG_DIR}/bonnie.env"
echo "Created config at ${CONFIG_DIR}/bonnie.env"

# --- Systemd service ----------------------------------------------------------

cat > /etc/systemd/system/bonnie.service <<SVCEOF
[Unit]
Description=BONNIE GPU Host Agent
Documentation=https://github.com/${REPO}
After=network-online.target docker.service
Wants=network-online.target
Requires=docker.service

[Service]
Type=simple
User=bonnie
Group=bonnie
EnvironmentFile=/etc/bonnie/bonnie.env
ExecStart=/usr/local/bin/bonnie
Restart=on-failure
RestartSec=5
LimitNOFILE=65536

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
StateDirectory=bonnie
ReadWritePaths=/var/run/docker.sock /var/lib/bonnie

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable bonnie.service
systemctl start bonnie.service
echo "Started bonnie.service"

# --- Health check -------------------------------------------------------------

echo "Waiting for BONNIE to become healthy..."
HEALTHY=false
for i in $(seq 1 30); do
    if curl -fsSL -o /dev/null "http://127.0.0.1:${PORT}/health" 2>/dev/null; then
        HEALTHY=true
        break
    fi
    sleep 1
done

if [ "$HEALTHY" != "true" ]; then
    echo "Warning: BONNIE did not become healthy within 30s. Check: journalctl -u bonnie -f"
    exit 1
fi
echo "BONNIE is healthy."

# --- Phone home ---------------------------------------------------------------

echo "Registering with control plane..."
case "$ADDRESS" in
    *[!A-Za-z0-9.:-]*)
        echo "Error: --address may only contain letters, digits, '.', ':' and '-'."
        exit 1
        ;;
esac
REGISTER_BODY="{\"registration_token\":\"${REGISTRATION_TOKEN}\",\"port\":${PORT},\"auth_token\":\"${AUTH_TOKEN}\""
if [ -n "$ADDRESS" ]; then
    REGISTER_BODY="${REGISTER_BODY},\"address\":\"${ADDRESS}\""
fi
REGISTER_BODY="${REGISTER_BODY}}"

# No -L: a redirect must never re-send the auth token elsewhere.
RESPONSE=$(curl -fsS -X POST \
    -H "Content-Type: application/json" \
    -d "$REGISTER_BODY" \
    "${SERVER_URL}/api/v1/agents/register" 2>&1) || {
    echo "Warning: Failed to register with control plane."
    echo "Response: ${RESPONSE}"
    echo "The agent is running but you may need to register it manually."
    exit 1
}

echo "Registration successful!"
echo "${RESPONSE}"
echo ""
echo "BONNIE agent is installed and registered."
