"""Client and agent registry for the BONNIE GPU-host agent.

BONNIE stays in Go; its HTTP API is the cross-language contract. The client
targets BONNIE as it behaves today, framing defects included, and works
around them tolerantly so it keeps working unchanged once BONNIE is fixed.
"""

from flag_commons.bonnie.client import (
    DEFAULT_FETCH_TIMEOUT,
    DEFAULT_RETRIES,
    DEFAULT_TIMEOUT,
    RETRY_AFTER_MAX,
    RETRYABLE_STATUSES,
    BonnieClient,
    backoff_delay,
)
from flag_commons.bonnie.errors import (
    BonnieBadRequest,
    BonnieError,
    BonnieNotFound,
    BonnieUnauthorized,
    BonnieUnavailable,
)
from flag_commons.bonnie.models import (
    BenchmarkEvent,
    BenchmarkResult,
    BenchmarkSpec,
    ContainerInfo,
    CreateContainerRequest,
    DiskUsage,
    EngineSpec,
    ExecRequest,
    ExecResult,
    FetchModelRequest,
    GPUInfo,
    GPUMetrics,
    GPUSnapshot,
    HealthCheck,
    HealthReport,
    HealthStatus,
    ModelEntry,
    PairedRunSpec,
    SystemInfo,
    SystemInfoResponse,
)
from flag_commons.bonnie.registry import (
    STATUS_OFFLINE,
    STATUS_ONLINE,
    STATUS_UNAUTHORIZED,
    Agent,
    AgentRegistry,
    BonnieAgentsChecker,
    NoAgentsRegistered,
    NoOnlineAgents,
    RegistryError,
    RegistryStore,
)
from flag_commons.bonnie.sse import (
    MAX_FRAME_BYTES,
    MAX_LINE_BYTES,
    SSEFrame,
    SSEOverflow,
    demux_stdcopy,
    parse_sse,
)

__all__ = [
    "DEFAULT_FETCH_TIMEOUT",
    "DEFAULT_RETRIES",
    "DEFAULT_TIMEOUT",
    "MAX_FRAME_BYTES",
    "MAX_LINE_BYTES",
    "RETRYABLE_STATUSES",
    "RETRY_AFTER_MAX",
    "STATUS_OFFLINE",
    "STATUS_ONLINE",
    "STATUS_UNAUTHORIZED",
    "Agent",
    "AgentRegistry",
    "BenchmarkEvent",
    "BenchmarkResult",
    "BenchmarkSpec",
    "BonnieAgentsChecker",
    "BonnieBadRequest",
    "BonnieClient",
    "BonnieError",
    "BonnieNotFound",
    "BonnieUnauthorized",
    "BonnieUnavailable",
    "ContainerInfo",
    "CreateContainerRequest",
    "DiskUsage",
    "EngineSpec",
    "ExecRequest",
    "ExecResult",
    "FetchModelRequest",
    "GPUInfo",
    "GPUMetrics",
    "GPUSnapshot",
    "HealthCheck",
    "HealthReport",
    "HealthStatus",
    "ModelEntry",
    "NoAgentsRegistered",
    "NoOnlineAgents",
    "PairedRunSpec",
    "RegistryError",
    "RegistryStore",
    "SSEFrame",
    "SSEOverflow",
    "SystemInfo",
    "SystemInfoResponse",
    "backoff_delay",
    "demux_stdcopy",
    "parse_sse",
]
